name: My first work flow

on: push

jobs: 
    first_job: 
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: List and Read Files
          run: |
           echo "My First Github runner"
           ls -lrth
           cat README.md

        - name: Generate ASCII Artwork
          run: cowsay -f dragon "Run for cover, I am a dragon" >> dragon.txt

      #  - name: List the files
      #    run: ls

      #  - name: read the file
       #   run: cat README.md




