name: My first work flow

on: push

jobs: 
    first_job: 
        runs-on: ubuntu-latest
        steps:
        - name: Welcome message
          run: echo "My First Github runner"

        - name: List the files
          run: ls

        - name: read the file
          run: cat README.md




