name: Generate ASCII Artwork
on: push
jobs: 
    ascii_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4

            - name: List the files
              run: ls -lrth

            - name: Executing Shell Script
              run: |
               chmod +X ascii-script.sh
                ./ascii-script.sh

              